"""Assemble every result into reports/RESULTS_<kind>.md (numbers and figures only).

The document is generated, never hand-edited: rerunning the experiments and this script
reproduces it. Interpretation belongs in the author's own write-up.

    python scripts/build_report.py [real|synthetic]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]


def pct(x, d=1):
    return "" if pd.isna(x) else f"{x * 100:.{d}f}%"


def pp(x, d=2):
    return "" if pd.isna(x) else f"{x:+.{d}f}"


def md_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(map(str, cols)) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join("" if pd.isna(v) else str(v) for v in r.values) + " |")
    return "\n".join(lines)


def main(kind: str = "real") -> Path:
    res = ROOT / "results" / kind
    fig = f"../figures/{kind}"
    out = []
    a = out.append
    a(f"# Results: do equity anomalies survive reality in India? ({kind} data)\n")
    a("*Generated by `scripts/build_report.py` from `results/` - do not edit by hand.*\n")
    if kind == "synthetic":
        a("> **Dry run on a synthetic market with known truth.** These numbers validate the code, "
          "they say nothing about India.\n")

    stats_p = ROOT / "data" / "processed" / "build_stats.json"
    if kind == "real" and stats_p.exists():
        st = json.loads(stats_p.read_text())
        a("## 1. Data\n")
        a(f"{st['files']:,} NSE daily files, {st['first_date']} to {st['last_date']}; {st['rows']:,} security-days; "
          f"{st['securities']:,} securities after linking ({st['symbol_change_links']} symbol changes and "
          f"{st['isin_links']} ISIN links joined; {st['reused_symbols']} reused symbols split apart). "
          f"{len(st.get('missing_session_days_repaired', []))} sessions missing from the archive were bridged.\n")
    e1 = res / "e1_summary.json"
    if e1.exists():
        s = json.loads(e1.read_text())
        det = s.get("detector") or {}
        tv, vv = det.get("tuning", {}), det.get("validation", {})
        a(f"Splits and bonuses: NSE records from {s['detector_used_before']} "
          f"({s['record_stats'].get('ca_split_bonus_records_applied')} split/bonus factors applied). Before that, a gap "
          f"detector (tol {det.get('params', {}).get('tol')}, min ratio {det.get('params', {}).get('min_ratio')}) chosen "
          f"on records before {det.get('split_date')} (precision {pct(tv.get('precision'))}, recall {pct(tv.get('recall'))}) "
          f"and checked on later records: precision {pct(vv.get('precision'))}, recall {pct(vv.get('recall'))}. "
          f"It is used only in the extended sample. {s['unexplained_overnight_gaps_gt_40pct']} unexplained overnight gaps "
          f"> 40% remain and are listed for manual review.\n")
        cov = pd.read_csv(res / "e1_coverage_by_year.csv", index_col=0)
        t = cov[["sessions", "securities_traded", "exits", "distressed_exits", "universe_size_dec",
                 "universe_500th_liquidity_cr"]].copy()
        t["universe_500th_liquidity_cr"] = t["universe_500th_liquidity_cr"].round(2)
        a(md_table(t.reset_index().rename(columns={"index": "year", "date": "year"})) + "\n")
        a(f"![coverage]({fig}/e1_coverage.png)\n")

    g = pd.read_csv(res / "e2_gross_summary.csv")
    a("## 2. Gross replication (before costs and taxes)\n")
    rows = []
    for (port, kind_), grp in g.groupby(["portfolio", "kind"], sort=False):
        grp = grp.set_index("period")
        rows.append({"portfolio": port, "type": kind_, "CAGR full": pct(grp.loc["full", "cagr"]),
                     "CAGR train": pct(grp.loc["train", "cagr"]), "CAGR test": pct(grp.loc["test", "cagr"]),
                     "Sharpe full": f"{grp.loc['full', 'sharpe']:.2f}", "max DD": pct(grp.loc["full", "max_dd"], 0),
                     "NW t (mean)": f"{grp.loc['full', 'nw_t']:.2f}"})
    a(md_table(pd.DataFrame(rows)) + "\n")
    a(f"![deciles]({fig}/e2_decile_profiles.png)\n\n![cumulative]({fig}/e2_cumulative_gross.png)\n")

    n = pd.read_csv(res / "e3_net_of_reality.csv")
    a("## 3. Reality layers\n### Gross -> costs -> tax (Rs 10 lakh, impact k = 0.7)\n")
    t = n[n.period.isin(["full", "test"])].copy()
    for c in ("gross_cagr", "net_cagr", "net_after_tax_cagr", "net_cagr_brokerage_0.3pct", "net_cagr_spread_floor_10bp",
              "net_max_dd"):
        t[c] = t[c].map(pct)
    t["cost_drag_pp"] = (t["cost_drag_pp"] * 100).map(pp)
    t["avg_monthly_turnover"] = t["avg_monthly_turnover"].map(lambda x: pct(x, 0))
    cols = ["portfolio", "period", "gross_cagr", "net_cagr", "net_after_tax_cagr", "net_cagr_brokerage_0.3pct",
            "net_cagr_spread_floor_10bp",
            "cost_drag_pp", "avg_monthly_turnover", "net_max_dd"]
    a(md_table(t[cols]) + "\n")
    a(f"![gross net tax]({fig}/e3_gross_net_tax.png)\n")
    cap = pd.read_csv(res / "e3_capacity.csv")
    ct = cap.pivot_table(index=["variant", "capital"], columns="k", values="net_cagr", sort=False).map(pct)
    ct.columns = [f"k = {c}" for c in ct.columns]
    a("### Capacity (net CAGR, no tax)\n")
    a(md_table(ct.reset_index()) + "\n")
    a(f"![capacity]({fig}/e3_capacity.png)\n")
    ex = res / "e3_extended_sample_gross.csv"
    if ex.exists():
        e = pd.read_csv(ex)
        e = e[e.period == "full"]
        a("### Extended sample from 2007 (robustness; detector-adjusted before Jul 2010), gross\n")
        a(md_table(pd.DataFrame({"portfolio": e["portfolio"], "from": e["first_month"], "CAGR": e["cagr"].map(pct),
                                 "Sharpe": e["sharpe"].map(lambda x: f"{x:.2f}"), "max DD": e["max_dd"].map(lambda x: pct(x, 0))})) + "\n")
    sub = pd.read_csv(res / "e3_subperiods.csv")
    a("### Sub-periods (cumulative gross return)\n")
    a(md_table(pd.concat([sub[["period"]], sub.drop(columns="period").map(pct)], axis=1)) + "\n")
    tests = json.loads((res / "e3_tests.json").read_text())
    mt = tests["multiple_testing"]
    a("### Multiple testing\n")
    a(md_table(pd.DataFrame([
        {"period": p, "SPA p": f"{mt[p]['spa']['p_value']:.3f}", "best (SPA)": mt[p]["spa"]["best"],
         "Reality Check p": f"{mt[p]['reality_check']['p_value']:.3f}", "variants": mt[p]["spa"]["n_variants"]}
        for p in ("full", "test")])) + "\n")
    a(md_table(pd.DataFrame([{"variant": k, "Sharpe of excess vs EW": f"{v['sharpe_annual']:.2f}",
                               "luck threshold": f"{v['sr0_annual']:.2f}", "deflated Sharpe prob.": f"{v['dsr']:.3f}",
                               "trials": v["n_trials"]} for k, v in mt["deflated_sharpe_vs_ew"].items()])) + "\n")
    term = pd.read_csv(res / "e3_terminal_sensitivity.csv")
    a("### Delisting-return sensitivity (gross CAGR)\n")
    a(md_table(pd.concat([term[["terminal_return_distressed"]], term.drop(columns="terminal_return_distressed").map(pct)],
                         axis=1)) + "\n")
    dv = res / "e3_dividend_sensitivity.csv"
    if dv.exists():
        d = pd.read_csv(dv)
        a("### Dividends included (from Aug 2010)\n")
        a(md_table(pd.concat([d[["portfolio"]], d.drop(columns="portfolio").map(pct)], axis=1)) + "\n")

    h = pd.read_csv(res / "e3_hypotheses.csv")
    a("## 4. Pre-registered hypotheses\n")
    h["supported"] = h["supported"].map({True: "yes", False: "no"})
    a(md_table(h) + "\n")

    b = res / "e4_bias_summary.csv"
    if b.exists():
        bs = pd.read_csv(b)
        a("## 5. How much do data shortcuts inflate backtests? (gross CAGR bias, pp/yr)\n")
        piv = bs.pivot_table(index=["view", "fraction"], columns="rule", values="mean", dropna=False, sort=False)
        piv = piv.reset_index()
        piv["fraction"] = piv["fraction"].map(lambda x: "" if pd.isna(x) else f"{x:.0%} deleted")
        for c in ("equal_weight", "momentum", "low_vol"):
            piv[c] = piv[c].map(pp)
        a(md_table(piv) + "\n")
        a(f"![bias]({fig}/e4_bias_vs_deletion.png)\n")

    e5 = res / "e5_exposure_to_future_failures.csv"
    if e5.exists():
        x = pd.read_csv(e5)
        a("## 6. Exploratory (not pre-registered)\n### E5: why H6 was refuted - positions in companies that later failed\n")
        a(md_table(pd.DataFrame({"sample": x["sample"], "rule": x["rule"],
                                 "avg weight in future failures": x["avg_weight_in_future_failures"].map(pct),
                                 "monthly return on those positions": x["monthly_return_on_those_positions"].map(lambda v: pct(v, 2)),
                                 "monthly return on other positions": x["monthly_return_on_other_positions"].map(lambda v: pct(v, 2)),
                                 "drag (pp/yr)": x["drag_pp_per_year"].map(pp)})) + "\n")
        a(f"![e5]({fig}/e5_positions_in_future_failures.png)\n")
    e6 = res / "e6_value_short_sample.json"
    if e6.exists():
        v = json.loads(e6.read_text())
        a("### E6: value (earnings yield), short sample\n")
        a(f"{v['months']} holding months from {v['first_holding_month']} (NSE P/E files exist only from 2024). Top-decile earnings "
          f"yield: {pct(v['value_top_decile_gross_cagr'])} gross, {pct(v['value_top_decile_net_cagr'])} after costs; same-universe EW "
          f"{pct(v['ew_gross_cagr'])} gross. 95% interval of the gross difference: {pct(v['gross_diff_ci95'][0])} to "
          f"{pct(v['gross_diff_ci95'][1])}. Too short to test the value premium; reported so that it is not silently dropped.\n")
    a("## 7. Known limitations (stated, not fixed)\n")
    a("- Price returns are the primary series; dividend records exist only from Jul 2010.\n"
      "- Demergers and rights issues are not adjusted (no reliable factor in the records); large unexplained gaps "
      "are listed in `results/real/e1_unexplained_gaps.csv`.\n"
      "- The liquidity-ranked universe approximates, but is not, the Nifty 500.\n"
      "- Spread and impact are estimated from daily data; no tick data.\n"
      "- Exchange and SEBI fees use today's rates for all years; STT, stamp duty and taxes are dated.\n"
      "- Surcharge on tax ignored; tax paid pro-rata without triggering further gains.\n")
    a("## 8. Discussion\n\n*Written by the author.*\n")
    path = ROOT / "reports" / f"RESULTS_{kind}.md"
    path.parent.mkdir(exist_ok=True)
    path.write_text("\n".join(out))
    return path


if __name__ == "__main__":
    print(main(sys.argv[1] if len(sys.argv) > 1 else "real"))
