"""Write iris/KEY_NUMBERS.md: the handful of facts the abstract and video need, with sources.

    python scripts/key_numbers.py [real|synthetic]
"""
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]


def main(kind="real"):
    res = ROOT / "results" / kind
    L = [f"# Key numbers ({kind} data) - generated by scripts/key_numbers.py\n"]
    st = ROOT / "data" / "processed" / "build_stats.json"
    if kind == "real" and st.exists():
        s = json.loads(st.read_text())
        L.append(f"- Dataset: {s['files']:,} NSE daily files, {s['first_date']} to {s['last_date']}, "
                 f"{s['securities']:,} securities (dead ones included).")
    e1 = res / "e1_summary.json"
    if e1.exists():
        e = json.loads(e1.read_text())
        d = (e.get("detector") or {}).get("validation", {})
        L.append(f"- Split/bonus detector on held-out NSE records: precision {d.get('precision', 0):.0%}, "
                 f"recall {d.get('recall', 0):.0%}.")
    h = pd.read_csv(res / "e3_hypotheses.csv")
    L.append("\n## Hypotheses\n")
    L += [f"- {r.id}: {'SUPPORTED' if r.supported else 'not supported'} - {r.claim} ({r.evidence})" for r in h.itertuples()]
    n = pd.read_csv(res / "e3_net_of_reality.csv")
    L.append("\n## Gross -> after costs -> after tax (full primary sample, Rs 10 lakh)\n")
    for r in n[n.period == "full"].itertuples():
        L.append(f"- {r.portfolio}: {r.gross_cagr:.1%} -> {r.net_cagr:.1%} -> {r.net_after_tax_cagr:.1%} "
                 f"(turnover {r.avg_monthly_turnover:.0%}/month)")
    b = res / "e4_bias_summary.csv"
    if b.exists():
        bs = pd.read_csv(b)
        L.append("\n## Data-shortcut bias (pp/yr of CAGR)\n")
        for view in ("survivors", "today's top 500 backwards"):
            x = bs[bs.view == view].set_index("rule")["mean"]
            L.append(f"- {view}: EW {x.get('equal_weight', float('nan')):+.2f}, momentum {x.get('momentum', float('nan')):+.2f}, "
                     f"low-vol {x.get('low_vol', float('nan')):+.2f}")
        x = bs[(bs.view == "vendor") & (bs.fraction == 1.0)].set_index("rule")["mean"]
        L.append(f"- all distressed exits deleted: EW {x.get('equal_weight'):+.2f}, momentum {x.get('momentum'):+.2f}, "
                 f"low-vol {x.get('low_vol'):+.2f}")
    e0 = pd.read_csv(ROOT / "results" / "e0_bias_by_deletion_pp.csv", header=[0, 1], index_col=[0, 1])
    L.append("\n## Synthetic prediction (E0, 100% of bankrupt firms deleted)\n")
    for rule in ("equal_weight", "momentum", "low_vol"):
        L.append(f"- {rule}: {e0.loc[(rule, 1.0), ('cagr_bias', 'mean')]:+.2f} pp/yr")
    L.append("\nFull tables: reports/RESULTS_%s.md" % kind)
    p = ROOT / "iris" / "KEY_NUMBERS.md"
    p.write_text("\n".join(L) + "\n")
    return p


if __name__ == "__main__":
    print(main(sys.argv[1] if len(sys.argv) > 1 else "real"))
